version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  bot:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
volumes:
  redis-data:
